# Generated by Django 4.0.3 on 2022-04-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('update_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('joke', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
                ('score', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('init_time', models.DateTimeField(auto_now_add=True, verbose_name='date started')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='date ended')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.SmallIntegerField(default=0)),
                ('joke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jom.joke')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jom.season'),
        ),
        migrations.AddField(
            model_name='joke',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
