# Generated by Django 4.0.3 on 2022-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date received')),
                ('photo', models.ImageField(upload_to='matrix')),
                ('telegram_id', models.IntegerField()),
                ('telegram_username', models.CharField(max_length=255)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
